import Config

# Configure your database
config :vr, VR.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "vr_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# ── Real-device (phone) testing ─────────────────────────────────
#
# By default we bind to 127.0.0.1 only. The dev server is not exposed to the LAN.
#
# To connect from a phone, enable DEV_BIND_ALL=true. That also opens HTTPS —
# getUserMedia only works in a secure context, and a non-localhost address
# cannot open the microphone over http.
#
#     DEV_BIND_ALL=true mix phx.server
#     → https://<your Mac's LAN IP>:4001/spike/recorder
#
# The certificate is self-signed, so the phone shows a warning. Trust it manually.
bind_all? = System.get_env("DEV_BIND_ALL") == "true"
dev_ip = if bind_all?, do: {0, 0, 0, 0}, else: {127, 0, 0, 1}

# The port is not read here. The PORT / HTTPS_PORT resolution rules live in
# config/runtime.exs alone, and runtime.exs overwrites the port on top of the config below.
# (Duplicating the rules across two files invites drift where only one gets fixed)
config :vr, VRWeb.Endpoint,
  http: [ip: dev_ip],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "IAH5TdkG5nc+mhrCtfIK5zFLJyZnUIkhPVHgC6m1XSmEUqeAJZwLLapcrz/Wm9Hj",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:vr, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:vr, ~w(--watch)]}
  ]

if bind_all? do
  config :vr, VRWeb.Endpoint,
    https: [
      ip: {0, 0, 0, 0},
      # runtime.exs fills in the port (default 4001)
      cipher_suite: :strong,
      certfile: "priv/cert/selfsigned.pem",
      keyfile: "priv/cert/selfsigned_key.pem"
    ]
end

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :vr, VRWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/vr_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :vr, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
