import Config

# Configure your database
config :vr, VR.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "vr_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# ── 실기기(폰) 테스트 ────────────────────────────────────────────
#
# 기본은 127.0.0.1 에만 바인딩한다. 개발 서버를 LAN 에 노출하지 않는다.
#
# 폰에서 접속하려면 DEV_BIND_ALL=true 로 켠다. 이때 HTTPS 도 함께 열린다 —
# getUserMedia 는 보안 컨텍스트에서만 동작하고, localhost 가 아닌 주소는
# http 로는 마이크를 열 수 없다.
#
#     DEV_BIND_ALL=true mix phx.server
#     → https://<맥의 LAN IP>:4001/spike/recorder
#
# 자체 서명 인증서라 폰에서 경고가 뜬다. 수동으로 신뢰해야 한다.
bind_all? = System.get_env("DEV_BIND_ALL") == "true"
dev_ip = if bind_all?, do: {0, 0, 0, 0}, else: {127, 0, 0, 1}

# port 는 여기서 읽지 않는다. PORT / HTTPS_PORT 해석 규칙은
# config/runtime.exs 한 곳에만 있고, runtime.exs 가 아래 설정 위에 port 를 덮어쓴다.
# (규칙이 두 파일에 복제되면 한쪽만 고쳐지는 드리프트가 생긴다)
config :vr, VRWeb.Endpoint,
  http: [ip: dev_ip],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "IAH5TdkG5nc+mhrCtfIK5zFLJyZnUIkhPVHgC6m1XSmEUqeAJZwLLapcrz/Wm9Hj",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:vr, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:vr, ~w(--watch)]}
  ]

if bind_all? do
  config :vr, VRWeb.Endpoint,
    https: [
      ip: {0, 0, 0, 0},
      # port 는 runtime.exs 가 채운다 (기본 4001)
      cipher_suite: :strong,
      certfile: "priv/cert/selfsigned.pem",
      keyfile: "priv/cert/selfsigned_key.pem"
    ]
end

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :vr, VRWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/vr_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :vr, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
